### ISSUE TITLE
builds for Fedora 38

### ISSUE THREAD

**Issue by pschiffe** [yopito/fedora-epel-pkg#3]
Hello, could you add builds for the recently released Fedora 38 to the copr? Thank you.

**Comment by yopito** [comment]
hello, build is successful for f38 and burp2 (stable): 
see https://copr.fedorainfracloud.org/coprs/yopito/burp2/

However, I did not test it at runtime. Could you give a try ? thanks.

**Comment by yopito** [comment]
burp 3.1.4 (latest version) is also available here:
https://copr.fedorainfracloud.org/coprs/yopito/burp2-latest/

**Comment by pschiffe** [comment]
Thank you. I'm using stable version 2.x in these docker images: https://github.com/pschiffe/docker-burp
I've tested it briefly and it seems to work. Thanks again!

**Comment by yopito** [comment]
thanks for your test. enjoy burp
